name: "Bug report"
labels: [bug]
description: Report a bug or unexpected behavior
body:
- type: markdown
  attributes:
    value: |
      Before filling a new bug, please use the [search form](https://doublecmd.sourceforge.io/mantisbt/view_all_bug_page.php) to try to locate similar bugs at the old bug tracker.
      See [Making a bug report](https://github.com/doublecmd/doublecmd/wiki/Making-a-bug-report) page for guidelines on how to make a good bug report.

- type: textarea
  attributes:
    label: Version
    placeholder: |
      Double Commander
      Version: 1.0.9
      Revision: 222
      Commit: a844456e4
      Build date: 2022/12/03
      Lazarus: 2.2.5.0
      FPC: 3.2.2
      Platform: x86_64-Win64-win32/win64
      OS version: Windows 10 22H2 x86_64
    description: |
      Choose `Menu → Help → About` to find out.
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    placeholder: Detailed description
  validations:
    required: true
