blank_issues_enabled: true

contact_links:
  - name: I have a question about Double Commander
    url: https://github.com/doublecmd/doublecmd/discussions
    about: Please use GitHub Discussions to ask questions
