blank_issues_enabled: false

contact_links:
  - name: Feature request
    url: https://github.com/doublecmd/doublecmd/discussions/categories/suggestions
    about: Please use GitHub Discussions to suggest a new feature or improvement
  - name: I have a question about Double Commander
    url: https://github.com/doublecmd/doublecmd/discussions/categories/general
    about: Please use GitHub Discussions to ask questions
