name: "Feature request"
labels: [enhancement]
description: Suggest a new feature or improvement
body:
- type: markdown
  attributes:
    value: |
      Before filling a new feature request, please use the [search form](https://doublecmd.sourceforge.io/mantisbt/view_all_bug_page.php) to try to locate similar features at the old bug tracker.

- type: textarea
  attributes:
    label: Description
    placeholder:
  validations:
    required: true

- type: textarea
  attributes:
    label: Proposed technical implementation details (optional)
    placeholder:
  validations:
    required: false
